// <auto-generated />
using System;
using AmericaSecond;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AmericaSecond.Migrations
{
    [DbContext(typeof(FirstAndSecondContext))]
    [Migration("20200921095416_AddedBuiltYear")]
    partial class AddedBuiltYear
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AmericaSecond.Car", b =>
                {
                    b.Property<string>("LicensePlate")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Built")
                        .HasColumnType("datetime2");

                    b.Property<string>("Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("LicensePlate");

                    b.HasIndex("OwnerId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            LicensePlate = "1-NLD-73",
                            Built = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Make = "Renault",
                            Model = "Capture"
                        },
                        new
                        {
                            LicensePlate = "C#-13-37",
                            Built = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Make = "Tesla",
                            Model = "S"
                        });
                });

            modelBuilder.Entity("AmericaSecond.Country", b =>
                {
                    b.Property<string>("ISOCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ISOCode");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            ISOCode = "NLD",
                            Name = "The Kingdom of the Netherlands"
                        },
                        new
                        {
                            ISOCode = "USA",
                            Name = "The United States of America"
                        });
                });

            modelBuilder.Entity("AmericaSecond.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NationalityISOCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TelephoneNumber")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.HasKey("Id");

                    b.HasIndex("NationalityISOCode");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1974, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Eric",
                            LastName = "Kuijpers",
                            TelephoneNumber = "+31651312408"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1982, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Carron",
                            LastName = "Schilders",
                            TelephoneNumber = "+112"
                        });
                });

            modelBuilder.Entity("AmericaSecond.Car", b =>
                {
                    b.HasOne("AmericaSecond.Person", "Owner")
                        .WithMany("OwnedVehicles")
                        .HasForeignKey("OwnerId");
                });

            modelBuilder.Entity("AmericaSecond.Person", b =>
                {
                    b.HasOne("AmericaSecond.Country", "Nationality")
                        .WithMany()
                        .HasForeignKey("NationalityISOCode");
                });
#pragma warning restore 612, 618
        }
    }
}
